//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;

namespace Trib.Datos.Entidad
{
    [DataContract(IsReference = true)]
    [KnownType(typeof(deuda))]
    public partial class tipopersona: IObjectWithChangeTracker, INotifyPropertyChanged
    {
        #region Primitive Properties
    
        [DataMember]
        public int idtipopersona
        {
            get { return _idtipopersona; }
            set
            {
                if (_idtipopersona != value)
                {
                    if (ChangeTracker.ChangeTrackingEnabled && ChangeTracker.State != ObjectState.Added)
                    {
                        throw new InvalidOperationException("The property 'idtipopersona' is part of the object's key and cannot be changed. Changes to key properties can only be made when the object is not being tracked or is in the Added state.");
                    }
                    _idtipopersona = value;
                    OnPropertyChanged("idtipopersona");
                }
            }
        }
        private int _idtipopersona;
    
        [DataMember]
        public string nomtipopersona
        {
            get { return _nomtipopersona; }
            set
            {
                if (_nomtipopersona != value)
                {
                    _nomtipopersona = value;
                    OnPropertyChanged("nomtipopersona");
                }
            }
        }
        private string _nomtipopersona;

        #endregion
        #region Navigation Properties
    
        [DataMember]
        public TrackableCollection<deuda> deuda
        {
            get
            {
                if (_deuda == null)
                {
                    _deuda = new TrackableCollection<deuda>();
                    _deuda.CollectionChanged += Fixupdeuda;
                }
                return _deuda;
            }
            set
            {
                if (!ReferenceEquals(_deuda, value))
                {
                    if (ChangeTracker.ChangeTrackingEnabled)
                    {
                        throw new InvalidOperationException("Cannot set the FixupChangeTrackingCollection when ChangeTracking is enabled");
                    }
                    if (_deuda != null)
                    {
                        _deuda.CollectionChanged -= Fixupdeuda;
                    }
                    _deuda = value;
                    if (_deuda != null)
                    {
                        _deuda.CollectionChanged += Fixupdeuda;
                    }
                    OnNavigationPropertyChanged("deuda");
                }
            }
        }
        private TrackableCollection<deuda> _deuda;

        #endregion
        #region ChangeTracking
    
        protected virtual void OnPropertyChanged(String propertyName)
        {
            if (ChangeTracker.State != ObjectState.Added && ChangeTracker.State != ObjectState.Deleted)
            {
                ChangeTracker.State = ObjectState.Modified;
            }
            if (_propertyChanged != null)
            {
                _propertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    
        protected virtual void OnNavigationPropertyChanged(String propertyName)
        {
            if (_propertyChanged != null)
            {
                _propertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    
        event PropertyChangedEventHandler INotifyPropertyChanged.PropertyChanged{ add { _propertyChanged += value; } remove { _propertyChanged -= value; } }
        private event PropertyChangedEventHandler _propertyChanged;
        private ObjectChangeTracker _changeTracker;
    
        [DataMember]
        public ObjectChangeTracker ChangeTracker
        {
            get
            {
                if (_changeTracker == null)
                {
                    _changeTracker = new ObjectChangeTracker();
                    _changeTracker.ObjectStateChanging += HandleObjectStateChanging;
                }
                return _changeTracker;
            }
            set
            {
                if(_changeTracker != null)
                {
                    _changeTracker.ObjectStateChanging -= HandleObjectStateChanging;
                }
                _changeTracker = value;
                if(_changeTracker != null)
                {
                    _changeTracker.ObjectStateChanging += HandleObjectStateChanging;
                }
            }
        }
    
        private void HandleObjectStateChanging(object sender, ObjectStateChangingEventArgs e)
        {
            if (e.NewState == ObjectState.Deleted)
            {
                ClearNavigationProperties();
            }
        }
    
        protected bool IsDeserializing { get; private set; }
    
        [OnDeserializing]
        public void OnDeserializingMethod(StreamingContext context)
        {
            IsDeserializing = true;
        }
    
        [OnDeserialized]
        public void OnDeserializedMethod(StreamingContext context)
        {
            IsDeserializing = false;
            ChangeTracker.ChangeTrackingEnabled = true;
        }
    
        protected virtual void ClearNavigationProperties()
        {
            deuda.Clear();
        }

        #endregion
        #region Association Fixup
    
        private void Fixupdeuda(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (IsDeserializing)
            {
                return;
            }
    
            if (e.NewItems != null)
            {
                foreach (deuda item in e.NewItems)
                {
                    item.tipopersona = this;
                    if (ChangeTracker.ChangeTrackingEnabled)
                    {
                        if (!item.ChangeTracker.ChangeTrackingEnabled)
                        {
                            item.StartTracking();
                        }
                        ChangeTracker.RecordAdditionToCollectionProperties("deuda", item);
                    }
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (deuda item in e.OldItems)
                {
                    if (ReferenceEquals(item.tipopersona, this))
                    {
                        item.tipopersona = null;
                    }
                    if (ChangeTracker.ChangeTrackingEnabled)
                    {
                        ChangeTracker.RecordRemovalFromCollectionProperties("deuda", item);
                    }
                }
            }
        }

        #endregion
    }
}
