//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data.Common;
using System.Data.EntityClient;
using System.Data.Metadata.Edm;
using System.Data.Objects.DataClasses;
using System.Data.Objects;
using System.Data;
using System.Diagnostics;
using System.Globalization;
using System.Linq;

namespace Trib.Datos.Entidad
{
    public partial class bd_tributarioEntities : ObjectContext
    {
        public const string ConnectionString = "name=bd_tributarioEntities";
        public const string ContainerName = "bd_tributarioEntities";
    
        #region Constructors
    
        public bd_tributarioEntities()
            : base(ConnectionString, ContainerName)
        {
            Initialize();
        }
    
        public bd_tributarioEntities(string connectionString)
            : base(connectionString, ContainerName)
        {
            Initialize();
        }
    
        public bd_tributarioEntities(EntityConnection connection)
            : base(connection, ContainerName)
        {
            Initialize();
        }
    
        private void Initialize()
        {
            // Creating proxies requires the use of the ProxyDataContractResolver and
            // may allow lazy loading which can expand the loaded graph during serialization.
            ContextOptions.ProxyCreationEnabled = false;
            ObjectMaterialized += new ObjectMaterializedEventHandler(HandleObjectMaterialized);
        }
    
        private void HandleObjectMaterialized(object sender, ObjectMaterializedEventArgs e)
        {
            var entity = e.Entity as IObjectWithChangeTracker;
            if (entity != null)
            {
                bool changeTrackingEnabled = entity.ChangeTracker.ChangeTrackingEnabled;
                try
                {
                    entity.MarkAsUnchanged();
                }
                finally
                {
                    entity.ChangeTracker.ChangeTrackingEnabled = changeTrackingEnabled;
                }
                this.StoreReferenceKeyValues(entity);
            }
        }
    
        #endregion
    
        #region ObjectSet Properties
    
        public ObjectSet<contribuyente> contribuyente
        {
            get { return _contribuyente  ?? (_contribuyente = CreateObjectSet<contribuyente>("contribuyente")); }
        }
        private ObjectSet<contribuyente> _contribuyente;
    
        public ObjectSet<deuda> deuda
        {
            get { return _deuda  ?? (_deuda = CreateObjectSet<deuda>("deuda")); }
        }
        private ObjectSet<deuda> _deuda;
    
        public ObjectSet<documento> documento
        {
            get { return _documento  ?? (_documento = CreateObjectSet<documento>("documento")); }
        }
        private ObjectSet<documento> _documento;
    
        public ObjectSet<tipopersona> tipopersona
        {
            get { return _tipopersona  ?? (_tipopersona = CreateObjectSet<tipopersona>("tipopersona")); }
        }
        private ObjectSet<tipopersona> _tipopersona;

        #endregion
    }
}
